FWG/Controllers/CompanyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FWG.Controllers
{
    public class CompanyController : Controller
    {
        // GET: About
        public ActionResult Index()
        {
            ViewBag.Title = "Employees";
            
            return View();
        }

        public ActionResult Employees()
        {
            ViewBag.Title = "Employees";
            return View();
        }

        
    }
}

FWG/Controllers/IndustriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FWG.Controllers
{
    public class IndustriesController : Controller
    {
        // GET: Industries
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Industries()
        {
            return View();
        }
    }
}

FWG/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="CMMS, Computerized Maintenance Management System, M-PET, Software">
    <meta name="author" content="">
    <title>@ViewBag.Title</title>
    <!-- Bootstrap core CSS -->
    <link href="@Url.Content("~/css/bootstrap.css")" rel="stylesheet">
    <link href="@Url.Content("~/css/carousel.css")" rel="stylesheet">
    <link href="@Url.Content("~/css/custom.css")" rel="stylesheet" />

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body style="background-color: rgba(157, 187, 234, 0.10);">
    <div class="navbar-wrapper">
        <div class="container">

            <div class="navbar navbar-inverse navbar-static-top" role="navigation">
                <div class="container">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" href="#">Four Winds Group, Inc.</a>
                    </div>
                    <div class="navbar-collapse collapse">
                        <ul class="nav navbar-nav">
                            <li> @Html.ActionLink("Home", "Index", "Home", null , new { @class = "nav navbar-nav" })</li>                          
                            <li>@Html.ActionLink("Services", "Services", "Services", null, new { @class = "nav navbar-nav"})</li>
                            <li>@Html.ActionLink("Product", "Product", "Product", null, new { @class = "nav navbar-nav" })</li>
                            <li>@Html.ActionLink("Key Industries", "Industries", "Industries", null, new { @class = "nav navbar-nav" })</li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Company <b class="caret"></b></a>
                                <ul class="dropdown-menu">
                                    <li>@Html.ActionLink("Employees", "Employees", "Company", null, new { @class = "nav navbar-nav" })</li>
                                    <li><a href="@Url.Action("History", "History")">History</a></li>
                                    <li><a href="@Url.Action("Clients","Clients")">Clients</a></li>
                                    <li class="divider"></li>
                                    <li class="dropdown-header">Support</li>
                                    <li><a href="@Url.Action("FAQ", "FAQ")">FAQ</a></li>
                                    <li><a href="@Url.Action("Email","Email")">Contact us</a></li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>

        </div>
    </div>

    @RenderBody()

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script src="@Url.Content("~/js/bootstrap.js")"></script>
</body>
</html>